---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-resource-driver
spec:
  chartRef:
    kind: OCIRepository
    name: intel-gpu-resource-driver
  interval: 1h
  values:
    cdi:
      staticPath: /var/cdi/static
      dynamicPath: /var/cdi/dynamic
    nodeSelector:
      node.kubernetes.io/gpu: "true"

    securityContext:
      privileged: true

    mounts:
      devDri:
        enabled: true
        hostPath: /dev/dri
      sys:
        enabled: true
        hostPath: /sys
        readOnly: true
      udev:
        enabled: true
        hostPath: /run/udev
        readOnly: true
