---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ceph-csi-operator
spec:
  interval: 15m
  url: https://github.com/ceph/ceph-csi-operator
  ref:
    tag: v0.5.0
