---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceph-csi-operator-system

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./gitrepository.yaml
  - ./ceph-csi-operator/ks.yaml
