# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: argocd-manager-token
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: argocd-manager-long-lived-token
  template:
    engineVersion: v2
    data:
      token: '{{ index . "token" }}'
      ca_pem: '{{ index . "ca.crt" | b64enc }}'
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: argocd-manager-homeops
          property: token
    - match:
        secretKey: caData
        remoteRef:
          remoteKey: argocd-manager-homeops
          property: caData
