---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shoko
spec:
  chartRef:
    kind: OCIRepository
    name: shoko
  interval: 1h
  values:
    controllers:
      shoko:
        type: statefulset # SQLite DB
        containers:
          app:
            image:
              repository: ghcr.io/shokoanime/server
              tag: v5.3.0@sha256:1e7304146c1a8a24345a0be55896fae5d2b12515960564ae8afbb9345131b70a
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "Etc/UTC"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v3/Init/Status
                    port: &port 8111
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - "ALL"
                add:
                  - "CHOWN"
                  - "FOWNER"
                  - "SETUID"
                  - "SETGID"

            resources:
              requests:
                cpu: 700m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - shoko.beholdenkey.dev
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: shoko
        globalMounts:
          - path: /home/shoko/.shoko
      media:
        type: nfs
        server: titan.internal
        path: /var/nfs/shared/media
        globalMounts:
          - path: /mnt/anime
            readOnly: false
      dshm:
        type: emptyDir
        medium: Memory
        sizeLimit: 256Mi
        globalMounts:
          - path: /dev/shm
