---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./jellyfin/ks.yaml
  - ./seerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./nzbget/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./autobrr/ks.yaml
  - ./immich/ks.yaml
  - ./shoko/ks.yaml
  - ./wizarr/ks.yaml
  - ./kapowarr/ks.yaml
  - ./komf/ks.yaml
  - ./komga/ks.yaml
  - ./audiobookshelf/ks.yaml
  - ./recyclarr/ks.yaml
