---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nzbget
spec:
  dependsOn:
    - name: multus-networks
      namespace: kube-system
    - name: ceph-csi-operator
      namespace: ceph-csi-operator-system
  interval: 1h
  path: ./kubernetes/apps/media/nzbget/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false

