---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-plugin
spec:
  rules:
    name: intel.gpu
    labels:
      intel.feature.node.kubernetes.io/gpu: "true"
    matchFeatures:
      - feature: pci.device
        matchExpressions:
          vendor: {op: In, value: ["8086"]}
          device: {op: In, value: ["e20b"]}
          class:
            op: In
            value:
              - "03"
              - "0300"
              - "0302"
              - "0380"
              - "030000"
              - "030200"
              - "038000"
