---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-initdb-sql
data:
  immich.sql: |-
    CREATE EXTENSION IF NOT EXISTS cube;
    CREATE EXTENSION IF NOT EXISTS earthdistance;
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
