# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NFlOd3M5VlNxV2Z3dW9p
        TXJMajNTTGhpMktyL0VVS2Z2VkRBWkdoSlJVCjdXaHpOVGE1aVh5NU1lQVJEdmVx
        dWRLdzFMUzR4TjNvUUorQmVaY1pSaGcKLS0tIDJoUXV2OVAzeFZ2clhYa1dIUnFL
        d1RUQWw0R292RVk2TWg5d3ZlNnZzM1UKB6jH2PwFvFf6r9hLlirNA4NxNhsWCL7b
        vKgLfH8J2SWwOgb33GKwHYgfOZnskvUt6/JOEtaukJ7/ZvAYp0Iemg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:15:41Z"
  mac: ENC[AES256_GCM,data:kwflccZHBrbR2iYjDsdpWCl6mdDFS34ol4N8uSbaRlJCKzjiCcxnVNXcPeVEu2I9u9PKJdZM3iemERn3S2vklJOq91wCgZuld/EEwd3ND23uH8pRmsu981ETZasG6LHq538CcrA0KIdwD/4DXvZTgkHftjWfCpWQKTdTWHZyFqM=,iv:jWyWzb6X9FiO+WdhfAS/V1o7Pi5Bk5tPNeh/XmmHCKw=,tag:15yg2P3A4S+4+yjjchxlwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
