# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fdtyT5/VGblBXfK/VKa6DNGoTMazkEwNT6874WDsXatvK6nhU1hyZA==,iv:oAEh6ZJQxqTURx8J1QeDc4iz+J2T83uoI+2equAbRFA=,tag:bfTT7bTkeilweVh9wYlyGA==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3c4YkpmNDg3bFZwODhV
        N3FWWHN2U1FXZWVTZlROV054czhiWStHT25BCkZJQVRkSWdwdEtVY3VGUFNFNmt0
        K3hUZnJLUDI3VDZhbk5COFY3dlRzU0UKLS0tIGZLWTBkUy9XNWJlc1JUaFZ0OUl0
        VHRsdUVwdngwaFpSMWw1c1k2R3dPT2cKSZvFVavVbxUGkN905WXFV2vCAkNGzCMk
        GyvvPF3nTOFFClT5k5qvQSbag4FjUpqQvkmr/x+VFG7QCijM6ozgSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-20T17:17:53Z"
  mac: ENC[AES256_GCM,data:P60cEgBfHOK+3jp9Ln5dRInxaITq7vmCCCTCF6FPgH7SUeq9tqSYT2XQoDLK2htgYgvsImqiKg5f/WTAXKBwWDW3MajwHk0VYuLdeMBfntr9QVGOZ3FvzxKiA4bPQ5dRIXZGSc5fvL2fprIq2q22D6hOrBh19M6VD9aYq3eKzm4=,iv:Fl7r0aSCN1gEU87Si49+kKGgMoalSA/r5mDcKEhuwHI=,tag:s2V3UhhsgHk8SB4PD6YH7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
