# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSjhlQXM1UW5rOUNUdUNZ
        ckd3ZjQyU3k1TVF4MW5XWWMwSmxuTkZQRm13CkNkb2lYM2R6aUtranJQdFY3QnNs
        a1VGZjVGbDFYU3NqdlFnVWYxQXRhbzQKLS0tIFNZdUxUc3EwbjJvbHR5cjRQWE1y
        eFViZlh1MmJtOW55cWR2cTcvZTlnRjgKKW7UovCReiXMdHefQnBr9IkBfg0T6G9N
        1rteMzLxGL/iuPZhhnuj12ZNqLhtfHMspE48v8B7RWKsp1GJaGfU2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:27:34Z"
  mac: ENC[AES256_GCM,data:yP7b9sROmZmw47ID0iU0th2Y6GNS7YhbEm0S95BGqazJa3fKPSHXXEBbhNtlw/6iVm/q7uj7gXqumdf2e+GyGfgqfnDNYxAOuVosP3OWVNGSkSaBuCBr5sOyk7v84p4fDjXnNnm8AmumdjH8eAzZ4MbE1GFLxvpu2WQmlTwjIN8=,iv:tw7ol4Ca5tzrbKf+w6D0ykFNQ/wctPFH5MK2L927nuc=,tag:Eh+/SGk/FhY3pkLAArcqVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
