# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mVLdGhlHAj/xklWuHG85sHekUyOS7fuaWA+H09GVRY9tOgrI881HRQ==,iv:V+EvUD3ViHCnWeW79b9cPl+JaBbQ4G1Ry+myFFRQbhg=,tag:Qp9ZcCPq36Qquy3l88fkyA==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMVFrazEyTnR5SE40VVNm
        U1FPZHptM2xKS3lnVlJDRkVta09tR1ZydzFrCjN0dW9wTG5YcSs1cERSVWpzTjYx
        cktNMDdzd3JveWsxSGMrUS9EcGJCZE0KLS0tIGpIaXVCVmV0ajU1ZW1MZWRlYXZk
        WG8yeFJCNjFwQ2tSeG43ZlYwUzRwMzgKcV0ZKe+9Bdim1arwrxWzvXIT/b57k/bD
        lFF45xDtIlik9iBNTKW3MdThvY/+MFEFXKHsKX2hIgfPdmQ9nKih+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T01:03:31Z"
  mac: ENC[AES256_GCM,data:iOEwek0fV7362zGgkbI0chXQ5oG/8XKmNucA5xjHehkMrWcbsZ3Wsuc864zSlNGpuxtnWIRzDLY4uY39SNV630MP8X7WJehViJGjYUK+epz4E1b4OxfUZSy3TqZBILqWtOPfKkbB7/9Vxf+AUonCUTevQtXLrHiXIiTaBMdVSoQ=,iv:hQLvp1XJ+i0GO2YXKnQ2gv4CfeRbJAzq7CKLAbqZCTM=,tag:pNEoE4gm9B235vq4GbZmZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
