apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:z9JmUVEZX0oQx1/OdgDJ7CNW+XZTh436f67Ad18RaQby49LbRKG/HQ==,iv:g+r0WEcLRY+7j0/UmCQb3+fiAdacyJR1vhjGx/i3Inc=,tag:xIVnsrwoS5KVQaOJkaT7YQ==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR1kwT01zTHBGaE9qZmFF
        VEl2VnhMV2VmamhLWWFwNHUrWW1ZTG5JYnc0CndCUWtyc3ZYZkdNdnFHbU53czhR
        UzR6SVphZW1PZ0FPZklZcldxb09JQzAKLS0tIHlxc2NRV1FVckY0aFJqcDMzdGNX
        VmoxYVdnMWhkTXJ1VGE5dFZXWlcyRzgKX+y3aMOV97PJarT3tVZNqC28nTft2AJo
        ULdzTRNoJUtYTituvQbnDSInHTeL8EC3LdVDoFSazbjbUroWVAXVjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:59:04Z"
  mac: ENC[AES256_GCM,data:ig/LIT5kVPViTFeI5wUNYUxIdjXbegzi/E6OAxT823CC3nu46di6gY2fnxwGLp6qHZwsNw4yTAsWPFt7DqazMxVe4lR+xww4ffPVCdAxSMPu6Xl3gF4JdFs6DEuWzyIKRW6iATZSI2pp5f6LWcqe5OvsntQnLcaoqW/CiGLy+Iw=,iv:3K0HWVwdeIqs6NZKWAWLxb2Wn6TELUiWO88CZmD/pe0=,tag:ftt02N6yy2uBNQdsaqKiOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
