apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:y83CbfjkJtjPwdt6PAaV,iv:rC5EajdQ8IrdFUMlAq5dmkPXIBhfNsDVnuAMjHKTNBA=,tag:My+XaruuP4XO3WSkDGq+1A==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNGptUDRqYzR0UG91enZQ
        NkprSk5QOTVCYndRdDRHT1lNSFhQWGI5L1NBCk5rOEtGTkxJY1o2ZDdLSmxGVlhX
        cG5zdUlEZTRXWTJPdUNQOU8wQmFVMTgKLS0tIGZDMzdvQXl5QTMvTUJrcTNsOGJt
        MnVXVnJZTWF2OWF6WTZXZUt3eE04V1UKH8C8HcCeR63iiBaDK3s7IvH5vDOfeFWf
        OV3J5dCgmoZpUOP9EatjGF6HvVa9jjNII3Vf2/+1a0f277QsTwHQOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T15:49:30Z"
  mac: ENC[AES256_GCM,data:E4CN9qPEAnnc5p8bcpWtim/kbEK5QDXtUmLkDmH1aVTkLGw6ysJQlDWqekaDkt1jEVg1CnwJRGrlCuC+KB3PJDWS0aqWXdW94cXO/OlWeK/t9Tqi7I+KfN0KgIBjfDOpmqpnc92r93TUy+ew4t3kcUKTFDtu0X1mSfL6mc4KxuQ=,iv:Hl7vbmhv2XafaGha44sCdtBwxBzmusujvfPcwScj0N4=,tag:7cQy+d9P5RNzazZr+uOQiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
