apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:iaLWVqNNbOKxRfI59rxe,iv:KkCbf924LfhGrkirWwhJgo9DuFJUPOLlEiRTZqlKM58=,tag:LCgI2GwhHrfKa5ejVK9uug==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZDJaS3Byem5JYXg0TU1N
        bTZUdWhjYUo2cE1NU3VCWVM4dXlNU0t3S3g0CjhyTW0wUjlxS3ZKVTdyM2xUQ0la
        TlBjaG80NDZQUzlyR1hWRjRwVjl1aEUKLS0tIGV3TUhpN2FPOGk4cmhpc1Y2L00w
        Ym9LNCtmNzY5WS8weXU0dEsvTThwZ0EKw4Hc2P7+c+uHPeXhd7lVSNaTJsP2z9Cz
        LC6bRH3oEqGy6VzHN8gMIqZ12RCsJjQSh/eSFSCkuMZkNE1DP0TWbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T15:31:40Z"
  mac: ENC[AES256_GCM,data:Wwkq7IK2EvjwDnn8qviYZgs1lt4sKvBbNLKBTLxYPP7VMxwL1Xmtdjruf2RdxGBh4VFNqBJo11fkKOtPQ3AY3tWMm4Z3EMzpVRyoDC+ROlJVT/W8eYDXuUToKkiOUpKjLM361dJ/I9LLnxTIZrz9k6E9LxTeiFGd/bKIu51uLek=,iv:FhdIlkyevLqNm6CK8uXDHT43kf9ZexJFxwz3AxWt/Tg=,tag:9gV4GsSDuc3M34BxvSJ1FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
