apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:t10y6VDHWZdRp5LcLt6mJ3QcXDs8zFCWE7SNGLVUq/ONG6ZXYvwWDnr89JKvZn5ELYSNtBbKbJEvdra5XQ9PI7y6fy1D7QybNcU=,iv:O2utkfj4QnGMfH01uenU81azuUFjs1z+3JIepK7QrME=,tag:pnRX/cKNr4aTB1gF1htWHw==,type:str]
sops:
    age:
        - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L1NVTE4wdDIvMGpMa05U
            U2RHeTNKVVZLODlUdndQSmFmd0pwcTErTTNrCkM3ejg4MkFPVGRqTFpHTVBXNW1l
            WVpjZzZGaGQzZnBKNnEyWENEWEZyUjgKLS0tIFRPY2RCdHNxMGpSRkJnQzBXVTJl
            UHlKWVJYd2p1a0VxMXY2RVEzMUZlOXcKB67M6MmA/WqN1faB3E0bl3NHVJ6DR36A
            7k9WyTe/2pBMYMlzk3nWl96fPg/Wx1eneH2fuUGONi4FaHF+tUprsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T16:02:02Z"
    mac: ENC[AES256_GCM,data:chrCw2c0zcp4EYeILeSgppxzI5KbxxC30z1UwBq5baXEj8E8DoP16XOwemFnK07w3AGrLmN93FSKLFqOZ9WSDR/0nDI/5koY2w/LmDyCSH25rqmKmfV+grqXPdCJuAB0c4s9USiID5HyarGfIBX9s5Zz46dJr3OSZWtwVQQMa40=,iv:wP2bSr7wwy8gvSLXDc/LHy714ME4suhPalYV83mQkh4=,tag:kWjMsL5wtBlcrJQn/e+5mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
