apiVersion: v1
kind: Secret
metadata:
  name: youtube-cookies
type: Opaque
stringData:
  cookies.txt: ENC[AES256_GCM,data:Ndxp0OgMH5RmBCNfGbfSec90149dDDbXnxMky5XFX0jfE/8O4lZ9p/wl8P/LmF0GjeW0+fvzC7lHX0qk8UqkokccuBRZIFh0IVbINP+Vlnx8cUNdfK/nxQOo2R5fSJw47sVaJps3jKVgxksjnPnqJevMckFyyWv7YdapykvP4TFXuj5Rv78J2fynLn354KLhw/mxbAg9mSVXXEQZ0G2RKN2Vv+tP2phGRuxW9IhUNxR9mmonV7SiIdCrvNJ7mmGt66rQUn6au8YzrZgSJcXxeGu9ltFajeNmMmXAQ4zXE0sbz+M4c++H3P6yMgPKlfIa7Yv4j4/5bKVZpLMFk93BYuZjkF5+keE+G2GLMNGxjEtmK5Lpbx/n+6d2lkJfLhpc/okO1wQDJEy9jbbkgQestxGC63dLPDRr55zeqEiLOmgJWmYCOi9BfPMf8jOXrjGAPhK8kcVPNvPwU0q6b0j+g5qia6guMwLMdvD8bOKxfxx3KZF09P7eaxA3+g7TFGW4Kst5bVb4Rl/72AfbFyqUgOPKZCuKXeTfzgl7C+xbse/94dKx,iv:eJJ7XfMI150JKg6WRp9o4d8cpPwcU8MGXpLU5/06CS0=,tag:lDBm/BgCPzl2QYf3hVyXHQ==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWmtyU2NkMnZsU3NRNFB4
        SXlGaEtoZnpyWkltNWtvYi9WRUZrOUVWdEVzClBVOTNtVzdhcCtzRk9lV3ljOFRV
        dzdjV05NMnhyWng3Q2VWVVNRL1F2dVEKLS0tIEZ3OWhtRDlSVGFjeGk2UDRqcElS
        ZTcrMkg2bzJRRWpOYk1qZWZJa3d1UHcKt3kKgL5PfByIynrVcZPagpYVlQ6gfq9k
        Z9lyjcFTL1NifYHQQJH13qYtIvSSh6UDrImpdwBoy1mAkkYxUrh1Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T00:40:17Z"
  mac: ENC[AES256_GCM,data:dMZvtUXVHJUdHJ68GmFbiriEJ4Je1+fAqQ88ZtMPTsn84iMnXRZI5p++sS6xHeY2k0J/czblcBGi7IAeeOARwX/nkDp8YZT6xa9YETKXoTSUV6rNmmDkTR3Wi9o6VrKJeSgtKj1hkITmwZNafXOosrBRpJWQqBXNYetefebW7fQ=,iv:OPSuSLcqnJ9YWL8WT1HGPeABBd486BxLTzuybLIrCC0=,tag:xLhI98Z4bhWXlGeP1NGCxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
