# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Yu9mlwOZkuTifesjINic+rxaRkZBZBLbPNEc0/5C8eM=,iv:0sJ0O3wemzvdvWAl+qw6ifp9dwPG19NHQ9wUUKqD+q8=,tag:VcubKKxfR9SNMc2x1mQzWw==,type:str]
sops:
    age:
        - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RmI5T283VXV1eWZ5R20w
            NHJEdWozcHUweDk2eGpxQXRLZUcvb3J1OW5RCkhOUEV0QU9sbVI5cjhUOFlMQW1v
            N21UdU1yM1JwYk9TRjBwZUlNZHBrcFEKLS0tIEVUKzBpcVZaaXgxenBaMVFpU3Nn
            MmNIeE44bGcrdzhnVzBJaGdyZGpoUDQKpdRDQzMdFS+CBXId6AOSiUkwY2T9HQBP
            +U2kNd46dDjnUQ6mB8ssTY4LxueGb7bn5j0VUq60Wj3KaY13+1GcmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T20:02:32Z"
    mac: ENC[AES256_GCM,data:rZx6r4foyR76sPhVocZSFv4y1EdpPxI+haxE45H6F9nEfF11HX3gzV6wTVDdp5LHEeugJlUbTrQQciwCMtc890bP8GPvmJdXXOq4sHLdTKMZHgJHN8MPzBan+6porFKLrSUrVb8LHY2mfz0+/WP7RPYHfz0pf6sAX/gs/cxRjaI=,iv:9zQG7vLs/YC/G7QvweaUuY/obHIbkQgacwCfYaST79A=,tag:YLwYn1SO3wbnuCHNwVXp2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
