apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+fQxyvO80MYNBkI7i+vAyv4sC4Za89iy4y+CAiOLZ78=,iv:6Oil1eDM+5x0LnKLDKvtUudOOtvAzQlmbbKgJa7N1o4=,tag:S2coaGxoFDsf/tAnJhbi+w==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc0krRXdEd2hYUjR3Sngx
        ZGVUYXRhTlNQQXhBNlhNQzA0NndXS09EVzJZCm1xajl6b1llTmlKM2ZabERPcW04
        ZjRYZEtwbkd5aDRvNVJLUzJQb0kwa28KLS0tIFcyT0dWREFNU3FnZ0dyblliL3NH
        YlNxMTZhbUNFNW41SVZabzByRDdyR1EKl7Jfi57YjNLdUZjjEwn5SER1kwCXoCLS
        IBDJoBJ1etGESd40EdH6vCGKfePow8YfqlqD3eKLl3eGAVptE+Qi+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:46:32Z"
  mac: ENC[AES256_GCM,data:ux/EZVF1lLpJ30lMvhmH8Kpvf8ZOuQutoPDSN9Jk+Lrc03XRadYDFgv+pyeaVX06jrR1GtfALCUpez6lQpNbFwa+amPYWb7ltydrjcH6PtUeCN1DoX/y2wKdu1b1XYCOw20l2lGSZ3K1LrKiQOIutuAlJQPB7a3q231UrRPhHDg=,iv:/D45mDx+mLkn05OdQZR9quOWCBpsdDqp0oYNXC1YoNA=,tag:avYRknd9c1flOPjUZWvNeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
