# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6S7gMG9xlBX5eojveDOv8+Y8AgIWgWefKlNgy/QVT7IvcwGTNl9Zhg==,iv:EEnpLXjXP2U7admejdgvf/Rm45Gi4ZpyXu7S4mLbYZs=,tag:W32KICQyGUDtNIMnWMoVCg==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RmI5T283VXV1eWZ5R20w
        NHJEdWozcHUweDk2eGpxQXRLZUcvb3J1OW5RCkhOUEV0QU9sbVI5cjhUOFlMQW1v
        N21UdU1yM1JwYk9TRjBwZUlNZHBrcFEKLS0tIEVUKzBpcVZaaXgxenBaMVFpU3Nn
        MmNIeE44bGcrdzhnVzBJaGdyZGpoUDQKpdRDQzMdFS+CBXId6AOSiUkwY2T9HQBP
        +U2kNd46dDjnUQ6mB8ssTY4LxueGb7bn5j0VUq60Wj3KaY13+1GcmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-20T17:17:53Z"
  mac: ENC[AES256_GCM,data:dMZUe222Prro+Vn3TvQ6/sHITZc/qZl5Zg5SZFFH2NR0hNz3VkjvxtLLevtdAP8fX0dbcjTkeua9knZXRiHk38aPG6ludO/sgkfZlbFreY2OgMgKQ2nwhOoOp1ns0/y02jNg5L0cwsdqVTJtQhTxbLkBDgwUQkL/r9Eh5EHpCdA=,iv:szSK1mKdY/qdmCnXyUAAqD9LTXYDt0fhuWnLOQ7Zg5A=,tag:QxI116ml4hjytFErgEO8ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
