apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Sf51RrENUpdAuXP+1vREGYTi9Lq9PJVghDE913kXASg=,iv:+44BwqwVfSTQrqnvH3utgj89q4Ug0oqGk0n4m0w8Nqk=,tag:5w+2QSk1RnMmKhaWbgSn1Q==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcWZzUmJSeDN6c3cybU91
        RlJnNGQ5L2swQjVhS0p0aVl5SEtZZVJFWDBZCjZCWVdJZVFZOHZNNWd6dzNkbmkz
        WWhNc1FpTGJ3dWlXaTl3MFJ4NmRyTlEKLS0tIFlOS2NtaWpLaWM3OVZaTUkxZUUz
        VmRzNzZrMVk0UGREelZkQ3V3TkVjSXcK35H2S9+4k0Prax1yFNYnQQWg05G55Wc+
        XkybTOCnyRLhAKRJcRpLmiCx4z3ROSpLvqQdhzTtw6kq9u+f/AoOvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T15:31:40Z"
  mac: ENC[AES256_GCM,data:a+qiiNeWc/vLVIlCdWDX+jzUJy/pVhSu2nHbDYcW+iYRpzdM1V3GhIPFEt+92X43dhjnRC+65PddHbQRXG/V4agStZGA2qRvxwKFwhKdeFI+14PfB7ZIDkfkICBegfWj2p2yVL2EnKPoo3lPbMB4o0hEW0ApfS6agWI4tjuEOsk=,iv:JMHuWxPhUSGFthg5TOB4pT4PXOWkNElJym/rQ5JEf3w=,tag:E9NNJmSJ+uCj8VaWdeVIPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
