# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHalFWMmFnMkZXRFdGdGQ3
        SHMwVE1qbzVLeDBXaFhnUXRraXFMY29Mb3l3CmFad2UwOG9yWTVWRnhUNkx4RzNy
        bkRndmNGbjJMM3JnRlBIVUlEZlZINzQKLS0tIFMvajlRSUM1UFppTmRVTzQvMmNX
        OGxhUEJkN1lzYnpGK3hIRVZaTC9Pa2cKg/yUCWi8y/+USfXahCzg8GEgyoGhzTcI
        SVw9MEJn58+hS+pEjHgk7dm2NmCxIiiNzn/EyckWl1QSV9cGqRwhmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:15:41Z"
  mac: ENC[AES256_GCM,data:M9Ydv5iGC5MZl/gQyeQxcqVwoEMpR6+OB2T6f3yfBWaG5FkZpLavsl+zlXJv4m9gbhe61N6k67IyHSimw+/tAElHvxF0MYHA8S9RMpalh1C+bkzS1RW/buyxqDHj5mVMwcIvQr7I3K4ehR61LqmlcKL7X+g6j5R9Q669V7BVlRc=,iv:mIGV50wDiW9L0YRe0UbUQFJhow7Stdu8tbhG+Zf8N3U=,tag:y+J9WxX2aVzjjHBhpk0Ozg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
