# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN01WbjFQK1h3N2ZqWS9h
        Tm8zMmRFdFA1VllqY2d2UTNpRUZSbFZDSEQwCktXMTJIN0NVS3JEQnhDdTFPSDA1
        UzFUMUhZamQyZWtMV2tWRXdzSjZrelEKLS0tIHZ4ZC9Oc3Q3M3RFU0VRdU0yZ1FF
        a21uWGFHUGtoM1ZTdkhFVjE2QWkvQjgKdShMAOuK2XUnU8yaN5zfglAy2bFAkxeu
        uJucgBfgXq1MyTyivc6oEkcsYtZRokx7QMFnxOO8HgFNfjFCzwqxNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:40:10Z"
  mac: ENC[AES256_GCM,data:2Svnck4cZ5XflRlvIqDAZ5JEh6F1oD2nf98oT/avudc1QAM65/DI/DDC0lvgOj5LI4jTsMQgmb+62kAq/HjUiqWomvWo4oFQDsPG5837EbfPXGTl10Ap8mBCD9Q5/6tYDXtYibKNgCXt4CqoxWRonWfTSquHPD6vwUY1MO59jYE=,iv:Qyh/skYJE/HCFfic/HEtGEzVJNZU4+mAw6rj5oPOhz8=,tag:oSZwVO3mrPtIk+mWZ05gZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
