# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd2NucGtpcE1mQ0xwdm5O
        aWRZQUFsZFE1MTJHb3M5NUtNYjJpRlljUGowCmE4d2FoQVhUQnAzYngvUmltbXlt
        V0FmV2F4NjR5akxTejYwN2lZTmNtZU0KLS0tIDh1OTR2WXlnamxqY0ZRVW42bjdz
        MHROeE44emhZUk54SEk0ZndIWmtwYWMKTwY7+eSxVZATbPRLjGcZXi4SVRyn2Ala
        qcew1FRGeYhgzevqkk6cODyDGCsX0BV3A1KP5la130u2/Q4pKKWNmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:23:14Z"
  mac: ENC[AES256_GCM,data:rH1spGrJ9+HSB9G7TvJe8SX/EVOyVJe6DiFvkIC+DHLzkmiKyQoLvlxCbVb9sX35mg2+it3Ck4ejtHINwY67kDIA2JVrhuP1GdHaNKxfYgnQT+MftllAhPtaaEZBFYqkkjOPatV5SSh4a4/ra7B1KgL06jTat1TkvANq/QT1wn8=,iv:DYMPptUPidjKTZCGe1dwVJNpSIFdAuHTm6Bn9povMFw=,tag:q1ckxNnlfxy7s73/hKcweA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
