# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacXZsMUpiZ0ZtM2l4emZj
        c1lyWFJ3TWhMalZ5NXdkaWRHUStMZytvRXdRCnREVW1yY0xpaVB3VVRzYVhodkw3
        dzlYd2FtUmpkektjOVNhcU54dTVVM3MKLS0tIHpxQjV5RzJ5NVUrMHZTVUk1aFJQ
        QlpWcDhGWWRGVlI4N0JCN1dDNWJVeEEKDo6n0TAbFb4K0RUYh5iZWd7bU6qbppu8
        2MNarWsk9q+zliIqkUTWSK6gFgzdXCUW2fXIXgVF8usXDls4CM6JTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:53:22Z"
  mac: ENC[AES256_GCM,data:gt4I7wDiFIFeNGZ/ouCwPSkDBJOi24QRu73aNi3AYo1EJvp92rHdHYo2CKLBYPSig/5M01XeXw1cW4DY88+q+McAqFyRSALUdNxxKXUU7NHFGAhSUWOotvosFNtMQj8Qr0vH4Quy+VWgxjOpld2mhI/ay0yDr5T0eo5nmakhVtY=,iv:K+MoNPJ/kGr11Yt2hXTi23bRk9y9s4v+Iw6RBR/EqEU=,tag:1pa457XnUNTVLjDBdi30ew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
