---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_HOSTNAME: "postgres18-rw.database.svc.cluster.local"
        DB_PORT: "5432"
        DB_USERNAME: "immich"
        DB_PASSWORD: '{{ .POSTGRES_PASSWORD }}'
        DB_DATABASE_NAME: "immich"
        DB_URL: 'postgresql://immich:{{ .POSTGRES_PASSWORD }}@postgres18-rw.database.svc.cluster.local:5432/immich?sslmode=disable&uselibpqcompat=true'
  dataFrom:
    - extract:
        key: immich
