---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres18
spec:
  instances: 3
  enablePDB: true
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart
  storage:
    size: 30Gi
    storageClass: ceph-rbd
    resizeInUseVolumes: true
  walStorage:
    size: 32Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  postgresql:
    extensions:
      - name: postgis
        image:
          # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgis-extension
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.1-18-trixie
        ld_library_path:
          - system
      - name: vchord
        image:
          # renovate: datasource=docker depName=ghcr.io/tensorchord/vchord-scratch
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.0.0
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
    synchronous:
      method: any
      number: 1
    parameters:
      max_connections: "300"
      shared_buffers: "1GB"
      max_wal_size: "6GB"
      wal_keep_size: "1GB"
      max_slot_wal_keep_size: "2GB"
      archive_timeout: "60s"
      wal_sender_timeout: "60s"
      wal_receiver_timeout: "60s"
      pgaudit.log: "all, -misc"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    shared_preload_libraries:
      - vchord
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cloudflare-r2-homeops-18
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-immich-init
      - name: openwebui
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-openwebui-init
      - name: tandoor
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: postgres-tandoor-init
