---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudflare-r2-18
spec:
  configuration:
    destinationPath: s3://cloudnative-pg/
    endpointURL: https://efbe7889ca1dc641c5f3864301f10aca.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: S3_ACCESS_KEY
      secretAccessKey:
        name: cloudnative-pg-secret
        key: S3_SECRET_KEY
    wal:
      compression: gzip
