---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres17
  labels:
    cnpg.io/cluster: postgres17
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: postgres17
      cnpg.io/podRole: instance
