apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vM0hSXKPFbUtc7+ckhJNimkYJtkF9kdLtIJ9cSKybtAuCHvBDLL2g9J6jAwPAiiIf0EXGgah33VStKvZPuml9Ikr7T2mTPMe0+QFfPUEmFhPmgguEba9o4Vqt+fw717l1il/D4LmmzaAhdfsHMlBTRWnN8BnCAWnJCqOZLhLExSC0cQp8ggTag5LGvG1g+dgF7StW7mxEhb4xZ229J3yadYrp8VIutELqcOxUX6/0RDQ8Yqb,iv:JdFDBJWGYY5wbItApSt6gTUEHTYc6aIz7TIoKKWrsjk=,tag:8If/FeCKiWNHcPkbWLD5Kw==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN3lBM2pJT1BBU1QzQVBr
        VXJJT015bE9hdEl4cDMwMDVFK0xrdE5VcldZCkJrZlgvZnRPWUg1eWRLSnFMSzYw
        dUFvYzFkUlo0alROZEY2NnJsbWF4YnMKLS0tIDBmbzNERmtGQ2tPcEJmSjc5bUNi
        Unl2TEM0bVlxMmdDaFdMYVl0eFBIUzQKbtGxYtTI09WBU6+2cA2coBkojshI+zt8
        TXbSuz3KmEGT72F7ZGiVM2biKDuFGJbRRdkN4QKWl0pLwpm5N3JENA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:37:08Z"
  mac: ENC[AES256_GCM,data:1K4Csl1OCRcXVN8SFn5GeLY+MKvHvydBCdnh0blFGH4AlHYEJH7+H37HKbBwDUhD1/wVDgdspvpGCAH/LzO/cT7BvMUzVvepdnYCGy5/9uWAPh8HN13v1MwQj1RKEmzy4IlVnec9lIz6j2CcMZIL4UEVHOP9eHfpz19QCaby6nA=,iv:y5lp90cJSPT5ZGb9dTOTFYRvSg2xV4WTkf5EKS5S6QE=,tag:EXxgPOGn2dQztQ9U6qaWwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
