# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ESFWzXgEe9D0OPT989g8uGNIq1N8QMddvG51vhUj4+MyhGj2zXgbYztT3O9li/7O1ZeT7x1LYjtYE8mXIz7ycfo3Ni1ZyuY53KXFD5JkUCWWUk5UOe7ZWbAck3vP/5YaUJ4OYbbal2kR9M1p3KGZHyRKfGsCH6cSrnWpJwcvJFglYAJNhRSKTGhqGLVCWBRgC5PHBiDGantNcvAMxuAOymKfrAo0KugEz9IYZK4Mnzc8XORU,iv:yHKKJkxk3x2QPe+U06NfqjesMLpFETtExgmLAAjjajc=,tag:YaM7NkunktNv8TKsNf/NtA==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQVp1SldBdnhmMS9XbmhD
        U0l0Ri95ZFBXempBVTdHSmpoUHdSZnUyQWtJCnJZZVYydFl0bnJ4WDd4RFRZQ2N3
        ZERna0w2YUo5MDBQN2QycEhNMUtiZHcKLS0tIHVVYTNVSk9TZkx0SHpCeU4wZUtk
        SVlJbCtuSkN2dGtQNG1oUEhMZDF6Q2MKjNXd0Hk+d+/S3tGYPwNGaYkPDXL0ZTJK
        wsmH/rcCuVw+0OVfXtv89jLTB/G+1pOqbfzXNpRbh2FyYSljGhW7dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:23:14Z"
  mac: ENC[AES256_GCM,data:i2JWKcZcb9N9ADQef0FTN/XVDg9KQSaKTIwmWH+5RgA5SS8xVRTj8O3qgXrn6Z5FGIAA6//qB9oEnwWbWQqLljJAKLFEQGLll7IjTxlyzSiTV9XvC2Ef35BzQA/CpuMuaoGEtPx28OGsIdyC5iJuoxl9ZQoum5SW6KkwJM5tmgY=,iv:JpL/6BsGPJB6JJB49F4cUjSosCZKzcwwt+ZufFmI4V4=,tag:DMGNCOco4+0Ty4ecwlzOwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
