apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:v5GX4WHRt22btSvCjy7i+sSkI28vq1wvX4DIYDGAD21mYTZCt8CVGr5ut+z41VNQm/704wGDOrRBlgKir4hGviUIrMw4QEPIgxGjLP7Oumip2DHXNDr42h1ZPeZOM+kXG+16ZAMSOwvTMmygoBnwtDD0eBHEN7TMkAQbPASIBY+BRueIth2fbd/oSZNsMxkXF7aD9OSrxCh/q1cTN6ZSr72vysgUWcG3TT2uIe/E71H4yFvV,iv:QoO67B3ysp3rejYGeu44fm0xeioSOneNoDIHy84DGno=,tag:804ql2TkrpA3LwvlNYgMrQ==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNm5rMzEvd1VkOVoydzBh
        dCtCazZUN2JuVGNDbTU2eDJONHdTV2dybkhNCmwwdWhDeW9zTTN2SnBGRCtRMkE1
        V1RYcDhySWtjYnk1UnRmL3pkSm0yV0kKLS0tIEpZRStSYnQ2UkZWTFh3OXdlUTVa
        bi80TDg2Y0g3VjlnaUJlOWNQTFNpWlUKOjahTy9P+AbdZTmHve8sHWDMyqp89TcE
        MjF2/L4+cERFOxBl3GJuuizBQKiLRNiIu6v5Rh/zSgqw6z0tnfTzoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:46:32Z"
  mac: ENC[AES256_GCM,data:9SgImsEoZdjSYs/2XPEDO4DffsPF4spnyKd8oDi258Xh/ZZ904mVI7mjBzmLdRwDoNlczFua/MjKJo2jlsara7MY/gHZl11eWkzbFzW0H32x1aN95filbAPFbZHGbCiVkM69fuFM/sIt8BoIXj3LuoaoaZhT5EVgq36TKd2qY6Q=,iv:jlJUa580p8T9TqrfzEmU7IXYsUE3dNgFgFxGwenpxLQ=,tag:SgNxzAxQ6bz6+pP5XU1oIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
