# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cQRKKWQZ/Rfuc/BYoSYn4Di7ilwNgFLw0gssu12o4lnvQK+ceN9Mg2q2ugg8iyS5VB0hZTQ0ES3kBmAmsTF0i1AjRntK1NhLcLdG8RnEd4n0ihwc0i7ZV6zaWXUTPm7vYP5z5AhioXqGFoxY9pc9+tbuBtjljdDo+/Hf64A9v1/M7u5WTM5DvzwP59mwqlNvIi8qG+FsafnkXbabtGMbQVI7jljHPzA6JkNu0Oz+Dzp99hyH,iv:tvtlWMjJJeA8h4S0ONDQPBPrt/SC/Y2LCr7ufva+X/g=,tag:RiuUdOdouyRiEqudlt93mg==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bmhsVjZkUll2Q3hIRzZ4
        c2l0elFBdTVlVnEydUVwdmJaMEZDZ3BLTlJVClEwWEl6bFlQeWxMNmI3VjQrd1ZO
        MW5yRkxLNTJJTVMzakU3Umgrc3F5NzgKLS0tIFNMVU83WkUrN0lGaEtUUTNjQ3hj
        cU4xWUFMK3FvcE9SSWVOSFNMNEdaS28Ke+fxFf7AU7zMAiAkxyvf2V5T8irKMw1H
        KcABLyyHWBfZuSF1LfUXaHGHMn570sOp2nNJsagQQLlYiymzPBIGww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:53:22Z"
  mac: ENC[AES256_GCM,data:1RsLwTu5JI25d/Vtf8QwQUGrySXGz4iv41hQxd6pXTx0EbmdIfDV/hKTfrPGNTBpBYgXVSX2R0nF6BeR7ld/QXMPy0wmPAUbKOkxPGnZvHA0xj6thyKlqy9l5f3k5dCU+sS3RfyLBbBIlM62QmI9023j6qSN7ym6EBOSDZQxpiM=,iv:adqXFtsnBmPfi9iykujcDPEy7ghHsnpsMdAeAljSHTs=,tag:qmN32ornuzsoazdaGoNe1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
