# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0G/JpyW9ZFQoVQLkH2vM3tixGMmUTWiAzyc6iPegOh9oF9pgaqsrGZFlvUVqVGA4iK5/APo7z2P3NbHWOXOcYAoFeB12H+WkNkIQbA4DgzXGrqyA+kAQrIRfIi+m+y5fHw+nyezHW1UXwN0egM15BRcui4aLbIUo8+1nqZ/imCvAbCzwoidCp/EKYXPPwfnv1ddQElVqw4Dlf+Ukxndnx5tA2SJaLGUZ9krqRgNmts8IXaMP,iv:abwcE+CZtDR/Iwr1gf1DqfNbExjnJlLIxKpHmyWIopk=,tag:Fkn9UM14f2w8KlfPOScX+A==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVhENVRqNjVEL2cwTENG
        aDAwQ2RPQzBzS0VjRDlLcUIrSUdxQ1Z3MGtjClZZdkNLTVZxd0ZCVTBKVnYvRmVJ
        RVFWS1Jva2EzRkkxVjB4N0hsOXc3ZTgKLS0tIHBIamtWU3NCVjdSdFFYNW5iL3Vv
        Q2NaVXN4bXd3LzlLOUNRN0tlYnBwelUK2cx30qNl6E6M5X8HTOUdWSMR2w7B68BU
        KnMu77t3GTm2GXI8jsbJeyuKEtMT9DcbQWQJgoKmN0MvFQi5H+HIeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:27:35Z"
  mac: ENC[AES256_GCM,data:olVpYzsZAr5Qbt+XVcGj1AlpLXvkVdnhrNgfmiscVKiCNt0rqlSAc3zGG0E92GlmrkjvA6qq9XbylGbLDOOXRhY0IoeW7lNRNazhCuVsUL1x6KSFGyRjrcSEKzgK8I5z5/h7y2I/x9haob4gBYOob7V2EZFEM8DUkBinSUGk+Ak=,iv:1G+OrdzNKO4BxN0xlG9MJVk9NeGaFIRfblACg4xkvIA=,tag:PBjV5xI6LSXDs7zCO/eJsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
