---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.1
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgis
spec:
  images:
    - major: 17
      image: ghcr.io/cloudnative-pg/postgis:17
---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: vectorchord
spec:
  images:
    - major: 18
      image: ghcr.io/tensorchord/cloudnative-vectorchord:18.2
