# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:mRf07Ddi0v4LudJpaXyRv9nWoLsj31ULZLjcLOb+zK60mqx09Na70Q==,iv:zZ6Qpi9A3q3TSz/PfYeHJYaZhY/w/gt6VlNp8UrIZZE=,tag:Kvgs+DCCxLKsu0r+fhcK5w==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUGFXQ0NscCtIdE5pOHhE
        VW9VVVJpcjBiVHZqei84dEUxdjlLZjloV0FZCmU4Qk95UFZhMEwrVFhMNTZmYkFY
        eEFCdTF1dmxVNHFnTmp3T0NHSXR0YVkKLS0tIE13c2JrbDROUjVqenl6QkVSUlBZ
        b3ZWL1RYNTEvbU11aTlZbm9rcWdFWUEKHnnFIPFmllxjf6oG+ZObAwKNidWwwVs7
        UVYYvpaEj5yjGFrHTJGJ601V6YZj1wtU6dNeaRja3r6SWIGkeF7Jog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:54:52Z"
  mac: ENC[AES256_GCM,data:7SmqNQ2XCnhF33DhJUeox0t3nXufbre5kwchZeWPOGlChRc0Ay6nOInMvBFH6B4izUlYujnaQ75LPhjrMu6YUX0nvpD3UGRYH3GLYwVmrtK9r/RKsvpF2RejYB/P2s7S7zvdIo0FhoZrgjcf0LgL3Wuzo2iwdF1vZjD5nXvYcFU=,iv:pEBsC/s/wIdoRJ7vp8nppnOeUn/mqJ9jOii7dBt4CS4=,tag:NBZjcpCJZ04NmBjHe/QXcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
