apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7hLB4yhI15XrLxSY2H4qd6YlYV5oa4E/3CSCnmyPHr/pVW8OlWRU/Q==,iv:XBgltRVts8miwHIVkKFDeD9gfeDjoh6RvHSY0UR4vsI=,tag:mm1te2ehSByRMxu4IPunNQ==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlb2lRNWhQNk5zdFRwYmg3
        S2lDcDdPSms1cWcxaWRIbkZ6QXdmRUhsV2lNCkdXTyttekwvRndKbGRJc0o1dGQ1
        bVN6Y0RldDhDMWxjNjJ4NC91MGNmTncKLS0tIDBHRnhKa3p1cmR6NVd3MFVZclB3
        bUh6VHJRWjgwYkpWQ2I1bXJCMlplcjgKMIhkpc7F/kMT/m/3FmvOOnr3uJIxLFU3
        lEhwMyF+Dkcmml6MmphBwtlhtx+UI0y7+lr3/ehIO9bQdy2n0BbBTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T15:31:40Z"
  mac: ENC[AES256_GCM,data:IhPqEva5F3zQgHl/tZoKCKH0y5sYSbShU+fSfC6EHjCryNJ1rPc04C9q0w2MK+oXMGd+wiCaIeFcg9aPIxp3VY/2pMzNu/giftDeW1TELBNcEAx6Qz6thyWUBElmFNGbQy9Xr3+WwlLy3SlcJTZ6tvu11azTHHqXPTzi0KYNnXo=,iv:H5jELLX/ixBfp+mS3l7eulnksNMEh0h5H6jgAvdnn7w=,tag:YP3Zz2T+cqq1IB0hmMFgGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
