# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndURLZWtDOXQza3BuZHhR
        UFpFL0lYT3hrR3pBSmV3K0VUSElyUWNoTm1ZCjQrQlgvNWM3NWVoblBuNFhXSnps
        QnlOZ1JZbjlReEN6TGlyVkZTQXZ3aU0KLS0tIE5JZWhIUVdhZXhIU0pYNUJwM0Zi
        bVlNWHdHaEdNVmpwVzhkNUNQbDZQNEEKhWcFaR51TTGjyCNubqoY+9600Z9Hzvzj
        lae0WNn9EMceuCwKBj6IVWDxcalxCYGFiFfXTdSIPGAqtEY/+gE95A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:40:10Z"
  mac: ENC[AES256_GCM,data:hHFZGFaDsbpiuOUJWQw5z94nngBpIVRzC46vweYfmuMbmGBm8SEpmZYGI2AgKSMv8muPRi5bcTUrKMZcAhymeg6O+T10S3r7foS2pBm5fOAz9FqYs8KBQZHm/7p7bKcghC4NQn+X+1I9ngdRVfp4AKlKkU1XNCCPyBbyd4NPn8I=,iv:Ad2fnMEkDfyl0g5MO7z1MR276UtATCK9M2BUof/oJ6I=,tag:8kqj+fxKOAKAqTxa+osmCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
