apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:EdRJw82JK80pZQcsaPuSTWWphcNIcuC3u04AZ4nqVcEua4gEVjGiDA==,iv:DDJJlWXeW0datX2Q0YuL2eyORoAPxC2Q9Ww1XDr6d4c=,tag:Dx+lJzSOpYgnb6J0Px1BMQ==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S05mR1hXa05ndWhtSlM2
        MGRDMG1nS210ODhzMUZyNU9NT05oRE5kYzA0CjJzME56UHBMV2wvcGNWK0dZODVa
        RGpvNDVKbFV1WFNNZVFFQjhnMUFmVE0KLS0tIDA2akZsU2tWaVZPQTNwTWxzUEtm
        d29EVzhWcUNNZjVORTlWOS85UlZRT1EKeRVzpFpm1Z7joFTq9VWgadsmA7/8tIXB
        DLr0IKiF7ilkGPUtvDdwG6mhKSuPxMQd/CWyauwwJyo6+gpiPbcikw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:37:08Z"
  mac: ENC[AES256_GCM,data:XCJhwyFVKfNYX4BPqSiGaaj3/Cf08zInqIetV+2/7e8Hld5hj7zVNxoPCJ08as3yVe2ltHDte0mKO4s1V961goyc92b4o7REGLYOtrrUpDXYS+dNCXOXbSGPvPMqkMYIp0Fwg7Lch1H5yj5ca240Ick+w8g+VtF6HQfoZPiLxlo=,iv:8PdUSBAn7lh6yT+ZUHGfenOEwQq400bitJg3QeXsy1w=,tag:YbzpLol+muCvpauX36KlDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
