# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa1crVm85RmJRRDIxTVV6
        eExQY0NtaGVPK1hhVVdmV0dMb2FoRm1JNDJnCmtBbk0wRlJxVWhmbzV0dWxZMXNm
        NDBHYVVGeFNFY0NsSTVObHM2M1U3NkkKLS0tIG5oV1NpdllhOVVDNWpMUmVTKy9O
        aTM2S2hVbzNKUzB6K2FSeDFDc1R6eFUKFYqA8Vi6Zqj2o3gvS8AMlbCIROniX7mL
        p9Fdhocjnms61LdpwNXD0e6ckkR0Y4S3hwLwtqBVzp+MsjSON6lKXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:27:34Z"
  mac: ENC[AES256_GCM,data:o67XcjcwDmGf6CXRE12ETldOAPynj+LClps2VEhGx/jrckROS4xRetr3rymv0IIcMG64P4Sna237a19uJiuzEKpyLuX/+iAy0MMjEozBvMcAApOQZHbn6gjnWd5RmaN3dbB3swd0z22dWjb2bp9Pklphy3cvPu7pixKZQbPHg8Q=,iv:QtqgMJs/KPohjGuB+J1Gle4hDkzpW51/hjBI6ZcOt+8=,tag:Zva7kyzW2LyadhgWgMlf4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
