# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:QHL2EC5exCjMvA61VHpG9OnE9C61AQEHMZH9DHTJ4Ewogz3UzTsFbA==,iv:9M3LYehIk3a9kDzDvkbxI+sm+TlWyALff2AZDori7so=,tag:3rezDcLV07fJtpUkxrzhwA==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K0hGT3c0ZGhmMVBtWmE0
        RmdYRHdtOG1NNXpOcjl4di9PL2VFVzZlbFgwCmo3MTR3RjRYZ2YxYU9ieFl2ZTd2
        anpkaFo3ZkpDRjdlenNzYTQ3WHMyTnMKLS0tIHRzM2NBNEp2RTdTQUU2d0VXU3FK
        RzlVOW51d0NsSnJkUkNieWtMZk5TcGsK62AZDQkUty3PHiM4oZMS+2New0AETsmC
        72KFnhDfXrVY2JFI0CCCMHrxGmDiqYkIYRaIFg8nqAZNp5GmDEog3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-20T17:17:53Z"
  mac: ENC[AES256_GCM,data:5ocQipSToxrve1GNcaQ9dQ/O0iirIjD8+kupr2Y1gq93P0g+oAbKKQLOcrxBzuUQfqfqHiapVz/l3D3kDz9xof3UJr1fTFV1SRSfgtVrjLBlnuYWD8nLvTkV3uBj8VCBk14fnWCMZajqBXTaL/duD3/zqafwb1YDUFOqrpx7Gw4=,iv:zuQ7boZBrtxEDV6YYJwBaE7WyUsSiLcKho0TfmfEJb0=,tag:xhLxnMiO+O2Q+Q/T42RO6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
