apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:tI605BMY2CZovWfrwAthTIg583jG0uGarUd/T8wVP5V3gfQah6i6gg==,iv:EJZgPbBoCDUNfI2AFVUL8Yi618hYemPXTJhuK9BUCgI=,tag:hCBdFKwvYLbh/6dnPlXj4Q==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cmRDbE5tYkJFMjNDT3pT
        VzRLa3k0V21iaDNqU24wMG9ieEEvZlZlZGtnCjV6VFh6clI2Mnl2dDJGeUVuWDdy
        U3JBYWJyejBhTko1ZTNjUlcvaEo1eUEKLS0tIGc2Q3dOK2lUSVRpamNXRnB4bGsr
        RUNXNDZTRThWTnpiMUNJbVhRQitNT2MKSArUrWpUqu4t6ucLagNrggXiphWYd9Tl
        h2o+6DqeKKieTzyw9LWHr5tRDWuJoqAu2xvhHrk8WrYL6MYVWj/YeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T15:49:30Z"
  mac: ENC[AES256_GCM,data:kS5EZfMCbsQzBSMEGIRGKkO1JqiKu73hHm5rQ1Z7zIPXFJHoisTMrM5J9IH58N63L0z0dXwJtDvhEOC5VAHO+tAuY+Nz1xX3iVn71QgRUqFuEVWKWCqGfeqnJLCBJ/HpByl9GMeaIgGLl5u8yA1A+TrqCH6xlNQsBcQdZNVqovE=,iv:qF9x02w0iMZQUoq8Xb2Hajn6kKAjeSMp1K0sBCIZZlQ=,tag:OpYKTwafW3NVjiNbnRxyuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
