apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4iUt5+Cr9cEINUrKUM/PcYso8v0pDYpRDTiyD3p1zWKtjTGJvSYPKw==,iv:ssNANOAKjJRoiX3rPZo9rzgSpOSxeahPuYq1SZUA0Tk=,tag:MXUeb+S08LOEkH7i5WEMig==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUhrcUpaaW9mcE1yaWdq
        WmhoR0JmTFh2Q3dZaUk1RXZVNjBmR1pNYlJvCjBUNmhZMTJLQzByaTVHOXh6WVBZ
        UWZSZWJqTGNjZzBzYy9lT3lUdkZVWEUKLS0tIFFGalJpZ2IxaWNGVDZzbkVUU2pm
        aVAvN2pLQmFiTW9pSnp4UFRwZCtaUEkKIA8bUe/vLl9w3RPcsrn65Q9TYUBKTGLp
        3hosIIj5Lp7CJJ3/BmXLUjWafqog+5OtGXo12loOj7L53vkbgkhCUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T01:59:04Z"
  mac: ENC[AES256_GCM,data:x3D1xT1hLIdjvLiWNtOMoe7vutjNAK9bNh6oLmYyR/gNa1GUpsWXgXUOxzLB990vheTYB0EmjDmD/7umbEcspjhyTIaw4sGdAbgjPk7bqeMfd4e1NZvtPQv9LlYmLgX1N6IAQo7QdbDNbvBwJ9hdqoprcbPJtO5C3lxU8Sm/Ydc=,iv:KHF+vQhQrAjzIl8fZr4APHdIAP0KN/NA3tg6RFml9rw=,tag:gHLZpPwg46ASMIiD4ZxERw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
