# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd2Zqb3cxdU5taUpOUzNX
        bDN3eS93cVY2TDRYWVo2RGJ5T0FlczdjZHpNCm8xVlREdFRsWHJHeDkrQXRQVDFh
        MWFML1ppV3dscEFwNHdyUi9XQmpsblkKLS0tIHI0UTl6S0F6Z1pyWHFzMWVubDZY
        Vmc2aDR0ay94THJlN0NzUTRCUlR3VlEKsGi03KItA/1Qtt7+1jq85DZ7PVTjYk5o
        1KT9TfDpGwUVSIzU+QDIqhAH+lMgRK6QhRxCmxgq7BbuXCIRtaU1cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:23:14Z"
  mac: ENC[AES256_GCM,data:5q4EF7hh2X4dK1LgGKMzNN4IQ3UDvVwx1KOIts99vB4d6b1ni2SfDZeEaVo6ccl6TAU/p0YeuAhwXoO+bhWCgQZFAwbkCPgX0R3RS1DHfiAozl08NE7Pn4+H88VLbz9vjic6WenEMaQBpWkRWUdpCOvMZUIBR+hsuFbNW31BoyY=,iv:H9VXR9tQgplNcqPwAoR0ZNKft6UFi2QAkpg9l+gxIhg=,tag:7boBJRUNjF4Y7CXGk5rmqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
