---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: database
spec:
  dependsOn:
    - name: cnpg-operator
      namespace: cnpg-system
    - name: ceph-csi-drivers
      namespace: ceph-csi-operator-system
    - name: cnpg-plugins
      namespace: cnpg-system
  interval: 1h
  path: ./kubernetes/apps/database/cloudnative-pg/clusters
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
