---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.40.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.40.20"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "homeops-controller-01"
    ipAddress: "192.168.40.22"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/qemu-guest-agent
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:cc:6a:a3"
        dhcp: false
        addresses:
          - "192.168.40.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
  - hostname: "homeops-controller-02"
    ipAddress: "192.168.40.23"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/qemu-guest-agent
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:5f:ba:ec"
        dhcp: false
        addresses:
          - "192.168.40.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
  - hostname: "homeops-controller-03"
    ipAddress: "192.168.40.24"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/qemu-guest-agent
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:c3:62:ae"
        dhcp: false
        addresses:
          - "192.168.40.24/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
  - hostname: "homeops-worker-01"
    ipAddress: "192.168.40.25"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - talos.auditd.disabled=1 # Less security, faster puter
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
            - siderolabs/qemu-guest-agent
    talosImageURL: factory.talos.dev/installer/6e4d7b492d86b4175d08c2ce5c694232b0ec2cd866f682f9ee1da19decc8e249
    controlPlane: false
    nodeLabels:
      node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b4:88:c3"
        dhcp: false
        addresses:
          - "192.168.40.25/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
    patches:
      # Load kernel modules
      - |-
        machine:
          kernel:
            modules:
              - name: nvidia
              - name: nvidia_uvm
              - name: nvidia_drm
              - name: nvidia_modeset
# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-vlan.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/controller-features.yaml"
