---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.40.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.40.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "homeops-controller-01"
    ipAddress: "192.168.40.22"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4d2f14467f85468b6b5ff0ba1747f7f0bcb97d351d516db0197885247093d6fd
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:48:f0:06"
        dhcp: false
        addresses:
          - "192.168.40.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
        vlans:
          - vlanId: 90
            dhcp: false
            mtu: 1500
  - hostname: "homeops-worker-01"
    ipAddress: "192.168.40.23"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4d2f14467f85468b6b5ff0ba1747f7f0bcb97d351d516db0197885247093d6fd
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:d8:1e:a3"
        dhcp: false
        addresses:
          - "192.168.40.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vlans:
          - vlanId: 90
            dhcp: false
            mtu: 1500
  - hostname: "homeops-worker-02"
    ipAddress: "192.168.40.24"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4d2f14467f85468b6b5ff0ba1747f7f0bcb97d351d516db0197885247093d6fd
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:79:98:47"
        dhcp: false
        addresses:
          - "192.168.40.24/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vlans:
          - vlanId: 90
            dhcp: false
            mtu: 1500
  - hostname: "homeops-worker-03"
    ipAddress: "192.168.40.25"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4d2f14467f85468b6b5ff0ba1747f7f0bcb97d351d516db0197885247093d6fd
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a0:1e:4c"
        dhcp: false
        addresses:
          - "192.168.40.25/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vlans:
          - vlanId: 90
            dhcp: false
            mtu: 1500
# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/controller-features.yaml"
    - "@./patches/controller/cluster.yaml"

