---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.40.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.40.20"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "homeops-controller-01"
    ipAddress: "192.168.40.22"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:cc:6a:a3"
        dhcp: false
        addresses:
          - "192.168.40.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
  - hostname: "homeops-controller-02"
    ipAddress: "192.168.40.23"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:5f:ba:ec"
        dhcp: false
        addresses:
          - "192.168.40.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
  - hostname: "homeops-controller-03"
    ipAddress: "192.168.40.24"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:c3:62:ae"
        dhcp: false
        addresses:
          - "192.168.40.24/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500
        vip:
          ip: "192.168.40.20"
  - hostname: "homeops-worker-01"
    ipAddress: "192.168.40.25"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9
    controlPlane: false
    nodeLabels:
      intel.feature.node.kubernetes.io/gpu: "true"
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b4:88:c3"
        dhcp: false
        addresses:
          - "192.168.40.25/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.40.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-vlan.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/controller-features.yaml"
