---
originRequest:
  originServerName: "external.homeops.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_DOMAIN}"
    service: *svc
  - service: http_status:404
