---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres18-immich
spec:
  name: immich
  owner: immich
  cluster:
    name: postgres18
  extensions:
    - name: cube
      ensure: present
    - name: earthdistance
      ensure: present
    - name: vchord
      ensure: present
  databaseReclaimPolicy: retain
