---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres18-tandoor
spec:
  name: tandoor
  owner: tandoor
  cluster:
    name: postgres18
  databaseReclaimPolicy: retain
