---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookshelf
spec:
  chartRef:
    kind: OCIRepository
    name: bookshelf
  interval: 1h
  values:
    controllers:
      bookshelf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          bookshelf:
            image:
              repository: ghcr.io/pennydreadful/bookshelf
              tag: hardcover-v0.4.20.91@sha256:fd6183d0eacf1cac6ce3a0c8ff2b0d5af9ddf2101141f6c86c928a136c9b2d95
            command:
              - "/usr/bin/catatonit"
              - "--"
              - "/entrypoint.sh"
            env:
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__LOG__DBENABLED: "False"
              READARR__SERVER__PORT: &port 80
              TZ: America/New_York
            ports:
              - containerPort: *port
                name: http
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: false
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 4000
    route:
      bookshelf:
        hostnames:
          - "{{ .Release.Name }}.beholdenkey.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: bookshelf
                port: *port
    service:
      bookshelf:
        controller: bookshelf
        ports:
          bookshelf:
            port: *port
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      entrypoint:
        type: configMap
        name: bookshelf-entrypoint
        defaultMode: 0755
        advancedMounts:
          bookshelf:
            bookshelf:
              - path: /entrypoint.sh
                subPath: entrypoint.sh
                readOnly: true
      media:
        type: nfs
        server: titan.internal
        path: /var/nfs/shared/media
        globalMounts:
          - path: /media
            readOnly: false
      run:
        type: emptyDir
        medium: Memory
      tmp:
        type: emptyDir
