---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager
spec:
  dependsOn:
    - name: cert-manager
  interval: 1h
  path: ./kubernetes/apps/cert-manager/trust-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-ca-bundle
spec:
  dependsOn:
    - name: trust-manager
  interval: 1h
  path: ./kubernetes/apps/cert-manager/trust-manager/cluster-ca-bundle
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cert-manager
