---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-csi-rbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ceph-csi-rbd-secret
  data:
    - secretKey: userID
      remoteRef:
        key: ceph-csi-rbd
        property: userID
    - secretKey: userKey
      remoteRef:
        key: ceph-csi-rbd
        property: userKey
