apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qfdBkN5/UqyHLrVDRzac,iv:jqqvkgOY0Tii12VLxIxzrHtcz15CJuVYDIn8a+wYksk=,tag:f0E20fa4mbvLcn4RbzYhPw==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bG5Lbi9mRldMSlNLOThp
        cUI5YXZ6RzgzZmhXaTlRcUM4UUxYbGJHN2cwCjdRcGxTZ2o0MnNsUFBJeFZLeDd1
        am54TUtRM0hXRkp3RDNlSThYeXUwM0kKLS0tIFpGWURoekl1a1ljYXQ4S0cyK1c4
        aHNlYlgrbUQwWnhnVVNuTkRXeEFiNFUKfwoD7xc1X+tbTDleyqaMQIPvoX0g2Tk+
        AySbKmsEUVvVP/xYZQjC+862ap45cC/S2nd2EnJ1QFdBmYWlawWTNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:23:14Z"
  mac: ENC[AES256_GCM,data:6vMaMs4hKLYpdZ99g6KTpVqbQv0Moeie1QowNRA/5csmnPpD+jkYLkJx98ez/PZarf5pUcm3TYBQyoQ9r4Zrf9ee8PtCZgFgCpFQOClEohJzkmpqgq0ys6zbwX5eWOY27gQGpc8EKcEtWwv9JQiPy41VImGCX8qN8K9f5KEIOAc=,iv:rA9sqxZ3lK0WFUuOLrMAx4/3zqvMzuP2ACTAwNKvu+M=,tag:PB97H7UPcLQMKBmS92OHgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
