apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:oFmMgOM1Ou4EE6NWuEdI,iv:QDUMKVQuE+Oe4EqIEJKcgApyWv/XouBVRHY/WFbj9Ho=,tag:A+hi/UZsq+HS/6XkqBILcQ==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaDF6YitOVEVleWU1SUNY
        blEyS0QxcWtHNlVoQWM2TG01YjN5a2hkNG44Cm1BdXFlN0M0ai9VTUdBekdFajBV
        OHRiSUtZOHIzT2JDM3N1bG9KcUZXN3MKLS0tIE5mTDlraWczcnJHTnAyRVBwWFBq
        OXFmQ2ZjUUVwTGVWQ0FickZTcEltL1UKA1sabVRRw+2nHgulfmh7Jckj0D7PWxzc
        B2dSCpDYDCiZQtFNSlMDio5FJ/Yhw9SKMKnlU241LZGN5exGhZht6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T01:03:31Z"
  mac: ENC[AES256_GCM,data:vjljx5/wRmHTqZCOulKfLmN6lUndpl383mBrWFM58k8o5haBEvPhcvCbfqN9Md8ZSdE9MeIJVqVq887vJpv6IphhwJHRWb+8V/KPrH6X4JyDL4YTdCwvU/kq5dD8W+ujeU087QWZPms9NNaUtgZPkx1fxp8cNSwv6OqdX5Tw8tA=,iv:uAPL3mYuksOJtB+BZf/+Bo5e/9ueKiMyw6larmtbXQ4=,tag:zTxNpblUwSKzWrCGkWEmJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
