apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xkO2w+Dh1YsXINzMsbnk,iv:msOpZ+AaZePjnV69LWBFlmAP52HB4B0aNdQb07iaNSk=,tag:L+0C5Oli/SkgfT3/WqqL8A==,type:str]
sops:
  age:
    - recipient: age1p5daxpzpd6d6vw2vhl4222ry4s2g4z2m5tyurrurs79e5k0xcpcqw37ntw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZVZPQW55eWkyWG5KYmZv
        ZzhpcUh5SnFsMDBjamhPQTl0WjQyVHJxd0dZCnhkZ01ZRE5mM2dBYkUycUFLSGhK
        ZVRJdmVRL3RQNGI3WnRUYWtpbmFMWE0KLS0tIGdESmgxcVNVRmppYlV5WUZTOENX
        dE5NVWNwZVUzTjRKSWd1WmVjVDFwem8KFDU/mkhIg2sut/pngcMySikSG/1PZp5D
        SI8kdpT7Ffy95nFjvcnK+UJmp/7isZP1TR+pv71HYJF2Ny/M+NBvww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-31T00:27:34Z"
  mac: ENC[AES256_GCM,data:4wM30T2X+xKRNJhcgZ0DXXPPIu//78FE8bwTD8yq5ZVBvvrCAt5lCwRkHF1fUmnkyReEVufaIupBX/VQxPaMRYbyA0ERdUho05kmAy8bHHkcBpTC+8+h8AClmAgREQCZ9TLpezQr2pa+L9xSknXRN3S/9sBHKOmDXJqtrIm3Q7M=,iv:k2KK+rm/+615gX8Xf0Ufo1FiPV5i2h61w4HPBsk70z0=,tag:vlOpEHpjzhINr9uDx/+vnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
