---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-operator
spec:
  interval: 1h
  path: ./deploy/all-in-one
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: ceph-csi-operator
    namespace: ceph-csi-operator-system
  targetNamespace: ceph-csi-operator-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-drivers
spec:
  dependsOn:
    - name: ceph-csi-operator
      namespace: ceph-csi-operator-system
  interval: 1h
  path: ./kubernetes/apps/ceph-csi-operator/ceph-csi-operator/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ceph-csi-operator-system
