---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "1023585"
  installID: "55894995"
  url: "https://api.github.com"
  repositories: []
  permissions:
    contents: write
  auth:
    privateKey:
      secretRef:
        name: github-app-pem
        key: key
