---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password32
spec:
  generator:
    password:
      length: 32
      allowRepeat: true
      noUpper: false
      symbols: 0
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password64
spec:
  generator:
    password:
      length: 64
      allowRepeat: true
      noUpper: false
